services:
    lesson_design_patterns.example:
        class: LessonDesignPatternsBundle\Service\ExampleService
        arguments: ["@lesson_design_patterns.collection.client"]
        
    lesson_design_patterns.collection.client:
        class: LessonDesignPatternsBundle\Collection\CollectionClient    
